version: '3.7'
# NOTE
# ports and passwords for production porpuses should be different or stronger 
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - 8888:80
    volumes: 
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on: 
      - backend
      - mysql
    networks: 
      - app
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: vet
      MYSQL_USER: doctor
      MYSQL_PASSWORD: 123456
    ports: 
      - "3306:3306"
    volumes: 
      - mysql-data:/var/lib/mysql
    networks:
      - app
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    links: 
      - mysql
    depends_on: 
      - mysql
    ports: 
      - 9000:80
    volumes:
      - ./backend:/var/www/html
    networks:
      - app
  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    container_name: frontend
    tty: true
    ports: 
      - 3000:3000
    volumes: 
      - ./frontend:/app
    depends_on: 
      - backend
    networks:
      - app
networks:
  app:
    driver: bridge
volumes:
  mysql-data: